wip: testcase stuff you know..

diff --git a/bin/points b/bin/points
--- a/bin/points
+++ b/bin/points
@@ -1,30 +1,99 @@
 #!/bin/sh -e
 
-pfile=/feedback/points
-new_points=$1
-only_if=${2:-0}
+usage() {
+    (
+    echo "usage: $0 [add_points] [skip]"
+    echo "usage: $0 [-M] [-p add_points] [-s|-e skip|error]"
+    echo " -M             | always use /feedback/points, even when there is an active testcase"
+    echo " -p add_points  | add so many points. Required without testcase"
+    echo " -s skip        | if the skip is not zero (e.g. 1), then points is only added to the maximum points and not to the points"
+    echo " -e error       | alternative format for above"
+    echo ""
+    echo "  If there is an active testcase, the points are wrote to the testcase folder."
+    echo "  Otherwise or if -M is given, the points are added to the master points file."
+    echo "  Note that for testcases, the max points is set by the 'testcase' command"
+    ) >&2
+}
 
-if [ -z "$new_points" ]; then
-    echo "usage: $0 add_points [if_this_is_zero]" >&2
-    exit 64
+master_file=/feedback/points
+
+# Read arguments
+master=
+add_points=
+skip=
+while [ $# -gt 0 ]; do
+    case "$1" in
+        -p) add_points=$2 ; shift ;;
+        -s|-e) skip=$2 ; shift ;;
+        -M) master="x" ;;
+        --) shift ; break ;;
+        -*)
+            echo "ERROR: Invalid option $1" >&2
+            usage
+            exit 64
+            ;;
+        *)
+            if [ -z "$add_points" ]; then
+                add_points=$1
+            elif [ -z "$skip" ]; then
+                skip=$1
+            else
+                echo "ERROR: too many positionals" >&2
+                usage
+                exit 64
+            fi
+            ;;
+    esac
+    shift
+done
+
+clean_points() {
+    case ${points:-} in
+        ''|*[!0-9]*) points=0 ;;
+    esac
+    case ${max_points:-} in
+        ''|*[!0-9]*) max_points=$points ;;
+    esac
+}
+
+if [ "$master" -o -z "$TESTCASE_ACTIVE" ]; then
+    # points is required when updating the master file
+    if [ -z "$add_points" ]; then
+        usage
+        exit 64
+    fi
+
+    # read current state
+    if [ -s "$master_file" ]; then
+        IFS=/ read points max_points < "$master_file"
+    fi
+    clean_points
+
+    # change state
+    max_points=$((max_points + add_points))
+    if [ $skip -eq 0 ]; then
+        points=$((points + add_points))
+    fi
+
+    # store state
+    echo "$points/$max_points" > "$master_file"
+else
+    out=$TESTCASE_DIR
+    if [ ${skip:-0} -eq 0 ]; then
+        # current points
+        points=$(cat "$out/points")
+        max_points=$(cat "$out/max_points")
+        clean_points
+        if [ -z "$add_points" ]; then
+            add_points=$max_points
+        fi
+        points=$((points + add_points))
+        [ $points -gt $max_points ] && points=$max_points
+
+        echo "passed" > "$out/status"
+        echo "$points" > "$out/points"
+    else
+        echo "failed" > "$out/status"
+        echo "0" > "$out/points"
+    fi
 fi
-
-# read current state
-if [ -s $pfile ]; then
-    IFS=/ read points max_points < $pfile
-fi
-case ${points:-} in
-    ''|*[!0-9]*) points=0 ;;
-esac
-case ${max_points:-} in
-    ''|*[!0-9]*) max_points=$points ;;
-esac
-
-# change state
-max_points=$((max_points + new_points))
-if [ $only_if -eq 0 ]; then
-    points=$((points + new_points))
-fi
-
-# store state
-echo "$points/$max_points" > $pfile
diff --git a/bin/stdio-diff b/bin/stdio-diff
--- a/bin/stdio-diff
+++ b/bin/stdio-diff
@@ -1,22 +1,31 @@
 #!/bin/sh
 
+error() {
+    if { >&9; } 2>&-; then
+        echo "[${0##*/}] $@" >&9
+    else
+        echo "[${0##*/}] $@" >&2
+    fi
+}
+
 case=""
 space=""
 allspace=""
 pass="ok"
 fail=""
-while [ "$1" ]; do
+while [ $# -gt 0 ]; do
     case "$1" in
-        -c) case="x" ; shift ;;
-        -s) space="x" ; shift ;;
-        -S) allspace="x" ; shift ;;
-        -p) pass="$2"; shift 2 ;;
-        -P) pass="" ; shift ;;
-        -f) fail="$2" ; shift 2 ;;
+        -c) case="x" ;;
+        -s) space="x" ;;
+        -S) allspace="x" ;;
+        -p) pass="$2"; shift ;;
+        -P) pass="" ;;
+        -f) fail="$2" ; shift ;;
         --) shift ; break ;;
-        -*) echo "ERROR: Invalid option '$1' for $0" >&2 ; exit 64 ;;
+        -*) error "ERROR: Invalid option '$1' for $0" ; exit 64 ;;
         *) break ;;
     esac
+    shift
 done
 
 diff="diff --suppress-common-lines"
@@ -26,10 +35,26 @@ diff="diff --suppress-common-lines"
 
 in=$1
 expected=$2
-out=/tmp/stdio-diff.out
+out="/tmp/stdio-diff-$$.out"
 shift 2
 
-"$@" > $out < $in
+if [ -z "$in" -o ! -r "$in" ]; then
+    error "ERROR: In file '$in' does not exists or is not readable"
+    exit 66 # EX_NOINPUT
+elif [ -z "$expected" -o ! -r "$expected" ]; then
+    error "ERROR: expected file '$expected' does not exists or is not readable"
+    exit 66 # EX_NOINPUT
+elif [ -z "$*" ]; then
+    error "ERROR: no command to execute"
+    exit 64 # EX_USAGE
+fi
+
+"$@" > "$out" < "$in"
+RES=$?
+if [ $RES -ne 0 ]; then
+    echo "${fail:-The solution program returned with non-zero exit code}"
+    exit $RES
+fi
 
 if [ "$fail" ]; then
     $diff -q $out $expected > /dev/null
diff --git a/bin/testcase b/bin/testcase
--- a/bin/testcase
+++ b/bin/testcase
@@ -1,65 +1,108 @@
 #!/bin/sh
 
-usage() {
-    echo "usage: $0 [-t title] [-p points_on_success] [-s skip] prog arg1 arg2..." >&2
-    echo " -t title   | title (display name) for this test" >&2
-    echo " -p points  | if test returns 0, then we give so many points for this test, else 0" >&2
-    echo " -s skip    | if not 0, then skip execution of this test. $0 will return with skip as the exit code" >&2
+_testcase_error() {
+    if { >&9; } 2>&-; then
+        echo "[${0##*/}] $@" >&9
+    else
+        echo "[${0##*/}] $@" >&2
+    fi
 }
 
-# Read arguments
-title=""
-points=0
-skip=0
-while [ "$1" ]; do
-    case "$1" in
-        -t|-n) title=$2 ;;
-        -p) points=$2 ;;
-        -s|-e) skip=$2 ;;
-        --) shift ; break ;;
-        -*)
-            echo "ERROR: Invalid option $1" >&2
-            usage
-            exit 64
-            ;;
-        *) break ;;
-    esac
-    shift 2
-done
+_testcase_usage() {
+    if { >&9; } 2>&-; then
+        echo "usage: $0 [-t title] [-p points_on_success] [-s skip] [prog] [arg1] [arg2...]" >&9
+    else
+        echo "usage: $0 [-t title] [-p points_on_success] [-s skip] [prog] [arg1] [arg2...]" >&2
+        echo " -t title   | title (display name) for this test" >&2
+        echo " -p points  | if test returns 0, then we give so many points for this test, else 0" >&2
+        echo "            | if there is no program to execute, then points is used as max points for 'points' command" >&2
+        echo " -s skip    | if not 0, then skip execution of this test. $0 will return with skip as the exit code" >&2
+    fi
+}
 
-if [ -z "$1" ]; then
-    echo "ERROR: not test executable" >&2
-    usage
-    exit 64
+
+testcase() {
+    local points res skip title
+
+    if [ "${EUID:-${UID:-$(id -u)}}" -ne 0 ]; then
+        echo "ERROR: '${0##*/}' must be run as root" | \
+            { { cat >&9; } 2>&- || cat >&2; }
+        exit 64 # EX_USAGE
+    fi
+
+    if [ "${OUTPUT_IS_CAPTURED:-}" = 'yes' ]; then
+        echo "ERROR: '${0##*/}' can not be run inside 'capture'" | \
+            { { cat >&9; } 2>&- || cat >&2; }
+        exit 64 # EX_USAGE
+    fi
+
+    # Read arguments
+    title=""
+    points=0
+    skip=0
+    while [ $# -gt 0 ]; do
+        case "$1" in
+            -t|-n) title=$2 ;;
+            -p) points=$2 ;;
+            -s|-e) skip=$2 ;;
+            --) shift ; break ;;
+            -*)
+                _testcase_error "ERROR: Invalid option $1"
+                usage
+                return 64 # EX_USAGE
+                ;;
+            *) break ;;
+        esac
+        shift 2
+    done
+
+    if [ "${TESTCASE_EXECUTED:-}" = 'yes' -a $# -eq 0 ]; then
+        _testcase_error "ERROR: the 'prog' is required when testcase is executed as a command"
+        _testcase_usage
+        _testcase_error "To use the context syntax, then add the following to the script: '. ${0##*/}'"
+        return 64 # EX_USAGE
+    fi
+
+    # Acquire a testcase directory
+    TESTCASE_ACTIVE=0
+    TESTCASE_DIR=/feedback/$(printf "%02d" $TESTCASE_ACTIVE)
+    while ! mkdir "$TESTCASE_DIR" 2>/dev/null; do
+        if [ ! -e "$TESTCASE_DIR" ]; then
+            _testcase_error "Failed to acquire '$TESTCASE_DIR' for the testcase"
+            return 73 # EX_CANTCREAT
+        fi
+        TESTCASE_ACTIVE=$((TESTCASE_ACTIVE + 1))
+        TESTCASE_DIR=/feedback/$(printf "%02d" $TESTCASE_ACTIVE)
+    done
+    export TESTCASE_ACTIVE TESTCASE_DIR
+
+    # Init testcase directory
+    echo "0" > "$TESTCASE_DIR/points"
+    echo "$points" > "$TESTCASE_DIR/max_points"
+    [ "$title" ] && echo "$title" > "$TESTCASE_DIR/title"
+
+    # If skip is not 0, then exit
+    if [ "$skip" -a "$skip" -ne 0 ]; then
+        echo "skipped" > "$TESTCASE_DIR/status"
+        return $skip
+    fi
+
+    if [ $# -gt 0 ]; then
+        # Run the actual test
+        capture -- "$@"
+        res=$?
+        points -s $res
+        # testcase has completed, unset vars
+        unset TESTCASE_ACTIVE TESTCASE_DIR
+        return $res
+    else
+        return 0
+    fi
+}
+
+if [ "${0%/bin/testcase}" != "$0" ]; then
+    # Pretty sure someone executed this file, so call the function
+    TESTCASE_EXECUTED=yes
+    testcase "$@"
+    exit $?
 fi
-
-# Resolve output path
-testnum=0
-out=/feedback/$(printf "%02d" $testnum)
-while [ -e $out ]; do
-    testnum=$((testnum + 1))
-    out=/feedback/$(printf "%02d" $testnum)
-done
-
-# Init output directory
-mkdir -p $out >&2
-echo "0" > $out/points
-echo "$points" > $out/max_points
-[ "$title" ] && echo "$title" > $out/title
-
-# If skip is not 0, then exit
-if [ $skip -ne 0 ]; then
-    echo "skipped" > $out/status
-    exit $skip
-fi
-
-# Run the actual test
-capture -o $out/out.txt -e $out/err.txt -- "$@"
-RES=$?
-if [ $RES -eq 0 ]; then
-    echo "passed" > $out/status
-    echo "$points" > $out/points
-else
-    echo "failed" > $out/status
-fi
-exit $RES
