Pass capture's stderr to the captured command as fd 9
This allows student code to write 3 lines per capture invocation to
the teacher's view in A+. However, it also enables writing errors from
helper scripts there too.

diff --git a/bin/pre b/bin/pre
--- a/bin/pre
+++ b/bin/pre
@@ -1,11 +1,19 @@
 #!/bin/sh
 
+error() {
+    if { >&9; } 2>&-; then
+        echo "[${0##*/}] $@" >&9
+    else
+        echo "[${0##*/}] $@" >&2
+    fi
+}
+
 class=""
 while [ "$1" ]; do
     case "$1" in
         -c) class="$class${class:+ }$2" ; shift 2 ;;
         --) shift ; break ;;
-        -*) echo "ERROR: Invalid option '$1' for $0" >&2 ; exit 64 ;;
+        -*) error "ERROR: Invalid option '$1' for $0" ; exit 64 ;;
         *) break ;;
     esac
 done
diff --git a/bin/title b/bin/title
--- a/bin/title
+++ b/bin/title
@@ -2,21 +2,26 @@
 
 element="h1"
 class=""
-stdout=""
-while [ "$1" ]; do
-    case "$1" in
-        -c) class="$class${class:+ }$2" ; shift 2 ;;
-        -e) element="$2" ; shift 2 ;;
-        -O) stdout="x" ; shift 1 ;;
-        --) shift ; break ;;
-        -*) echo "ERROR: Invalid option '$1' for $0" >&2 ; exit 64 ;;
-        *) break ;;
-    esac
+stdout="${OUTPUT_IS_CAPTURED:+x}"
+while [ $# -gt 0 ]; do
+	case "$1" in
+		-c) class="$class${class:+ }$2" ; shift ;;
+		-e) element="$2" ; shift ;;
+		-O) stdout="x" ;;
+		--) shift ; break ;;
+		-*) echo "ERROR: Invalid option '$1' for $0" >&2 ; exit 64 ;;
+		*) break ;;
+	esac
+	shift
 done
 
-if [ -z "$stdout" ]; then
-    exec >> /feedback/out
+if [ -z "$stdout" -a -w /feedback ]; then
+	exec >> /feedback/out
 fi
 
-[ "$class" ] && class_a=" class=\"$class\""
-echo "<$element$class_a>$@</$element>"
+if [ "$element" ]; then
+	[ "$class" ] && class_a=" class=\"$class\""
+	printf "<%s%s>%s</%s>\n" "$element" "$class_a" "$*" "$element"
+else
+	printf "%s\n" "$*"
+fi
